### ISSUE TITLE
Jsend.error does not compile when objs is None

### ISSUE THREAD

**Issue by sirotopr** [grouzen/play2-jsend#1]
Jsend.error works properly when called with `objs` containing some value:
```scala
JSend.error("My error message.", None, Some(Seq("foo" -> "bar")))
```
Though, when I pass `objs` as `None`, such as in:
```scala
JSend.error("My error message.", None, None)
```
or
```scala
JSend.error("My error message.")
```
I get the following compile error:

    diverging implicit expansion for type play.api.libs.json.Writes[A] starting with object StringWrites in trait DefaultWrites

Using JSend.error with an empty `objs` is the most common usage. Thus this bug is rather critical.
It happens with Play 2.5 and Scala 2.11, I did not test with earlier versions.

**Comment by grouzen** [comment]
Hello!

Thanks for your attention.
I know this bug, it was there from the very beginning.

That happens because of some inconsistencies in the core library (in our case it's Option type which doesn't provide well-typed None), and I still don't know the standard solution for this.
I didn't check this, but maybe it could be solved by using none[T] (well-typed Option) from scalaz.
